### ISSUE TITLE
Suggetstion: Change title color

### ISSUE THREAD

**Issue by nickontravel** [nagray/github-crash-course#1]
I think it looks better if the main title were a bit more orange

The styling rule could be changed like this

```css
h1 {
  color: #efa82f;
}
```
